export default {
    "langs": ["pl", "de", "es", "it", "hi", "ru", "bg", "tr", "ja", "id", "cs", "zh-Hant", "ar", "fi", "ro", "pt-BR", "fr", "hu", "nl", "sv"],
    "langs-android": {
        "id": "in",
        "zh-Hant": "zh",
        "pt-BR": "b+pt+BR"
    },
    "langs-android-res": {
        "pl": "pl-rPL",
        "de": "de-rDE",
        "es": "es-rES",
        "it": "it-rIT",
        "hi": "hi-rIN",
        "ru": "ru-rRU",
        "bg": "bg-rBG",
        "tr": "tr-rTR",
        "ja": "ja-rJP",
        "id": "in-rID",
        "cs": "cs-rCZ",
        "zh-Hant": "zh-rTW",
        "ar": "ar-rSA",
        "fi": "fi-rFI",
        "ro": "ro-rRO",
        "pt-BR": "pt-rBR",
        "fr": "fr-rFR",
        "hu": "hu-rHU",
        "nl": "nl-rNL",
	"sv": "sv-rSE"
    },
    "langs-web4": {
        "pl": "pl_PL",
        "de": "de_DE",
        "es": "es_ES",
        "it": "it_IT",
        "hi": "hi_IN",
        "ru": "ru_RU",
        "bg": "bg_BG",
        "tr": "tr_TR",
        "ja": "ja_JP",
        "id": "id_ID",
        "cs": "cs_CZ",
        "zh-Hant": "zh_TW",
        "ar": "ar_SA",
        "fi": "fi_FI",
        "ro": "ro_RO",
        "pt-BR": "pt_BR",
        "fr": "fr_FR",
        "hu": "hu_HU",
        "nl": "nl_NL",
	"sv": "sv_SE"
    }
}
