name: Translations merge

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge by label
        uses: devmasx/merge-branch@master
        with:
          label_name: 'lgtm'
          target_branch: 'main'
          github_token: ${{ github.token }}
